### ISSUE TITLE
Tag type 31 is not supported by this module yet

### ISSUE THREAD

**Issue by skushnarev** [BoogeeDoo/mcnbt#5]
Hello! Found an error.
There are two files:
colony 1.dat
colonies.dat
Both read correctly. And there is one file, as I understand it, it contains both of these files.
capabilities.dat

When I try to read it, I get an error:
```
D:\Projects\Colonial-Therapist\preload.js:44 TypeError: Tag type 31 is not supported by this module yet.
    at BaseTag.getNextTag (D:\Projects\Colonial-Therapist\node_modules\mcnbt\lib\base_tag.js:269:13)
    at NBT.loadFromBuffer (D:\Projects\Colonial-Therapist\node_modules\mcnbt\nbt.js:28:29)
    at D:\Projects\Colonial-Therapist\node_modules\mcnbt\nbt.js:157:12
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
```

I tried manually setting the int type in the tags.js file. Then it comes out similar but with id 75.

Mod repository link:
https://github.com/ldtteam/minecolonies/tree/1be0c6afa7ddd93c3ddfd17dff5653c9e468bcf0

https://github.com/ldtteam/minecolonies/blob/1be0c6afa7ddd93c3ddfd17dff5653c9e468bcf0/src/api/java/com/minecolonies/api/util/constant/NbtTagConstants.java

I couldn't find types there, I don't understand java.

NBTExplorer opens all three files correctly.

Thanks for the library
[dat.zip](https://github.com/BoogeeDoo/mcnbt/files/9354852/dat.zip)
!

**Comment by MikeWu597** [comment]
Same error occurred.

**Comment by skushnarev** [comment]
> Same error occurred.

I started using [prismarine-nbt](https://github.com/prismarinejs/prismarine-nbt)

**Comment by MikeWu597** [comment]
> > Same error occurred.
> 
> I started using [prismarine-nbt](https://github.com/prismarinejs/prismarine-nbt)

Exactly, the same. Prismarine-nbt worked well.
